name: SquidNuke
main: me.hqm.SquidNuke
api-version: 1.14
version: ${project.version}
authors: [HQM]
commands:
    squidnuke:
        usage: /squidnuke <player> [type]
        permission: squidnuke.nuke
permissions:
    squidnuke.nuke:
        default: op